import turtle
h = turtle.Turtle()
h.up()
h.backward(290)
def house():
  number = int(input("# of Houses: "))
  i = 0
  while i < number:
    length = int(input("Length: "))
    height = int(input("Height: "))
    dh = int(input("Door Height: "))
    dw = int(input("Door Width: "))
    distance = (length / 2) - (dw /2)
    chimney = input("Is there a chimeny (y/n): ")
    if chimney == "y":
      ch = int(input("Chimney Height: "))
      cw = int(input("Chimney Width: "))
      cd = ch - (cw * (3 ** .5))
    color = input("Color: ") 
    h.down()
    h.color(color)
    h.forward(length)
    h.left(90)
    h.forward(height)
    h.left(30)
    h.forward(length)
    h.left(120)
    h.forward(length)
    h.left(120)
    h.forward(length)
    h.left(180)
    h.forward(length)
    h.left(90)
    h.forward(height)
    h.left(90)
    h.forward(distance)
    h.left(90)
    h.forward(dh)
    h.right(90)
    h.forward(dw)
    h.right(90)
    h.forward(dh)
    h.left(90)
    if chimney == "y":
      h.right(180)
      h.forward(dw)
      h.forward(distance)
      h.right(90)
      h.forward(height)
      h.forward(ch)
      h.right(90)
      h.forward(cw)
      h.right(90)
      h.forward(cd)
      h.left(180)
      h.forward(cd)
      h.left(90)
      h.forward(cw)
      h.left(90)
      h.forward(ch)
      h.forward(height)
      h.left(90)
      h.forward(distance)
      h.forward(dw)
    h.up()
    a = distance + 20
    h.forward(a)
    i += 1
house()